### ISSUE TITLE
Link to existing library on server

### ISSUE THREAD

**Issue by andy47** [LycheeOrg/Lychee-Docker#102]
Hi, I'm trying to run lychee under Docker on Ubuntu 20.4. I'd like to link to my collection of photos that are sitting in a directory on the same server. I'm trying to figure out how to tell the docker container running lychee about my external directory full of photos. Should I add this to the running container as a volume? Any help or assistance is much appreciated.

I'm running lychee using docker-compose with the sample compose file from https://github.com/LycheeOrg/Lychee-Docker/blob/master/docker-compose.yml. All I've done to this is change the DB passwords.

**Comment by d7415** [comment]
> Should I add this to the running container as a volume?

In short, yes. If you mean an existing Lychee installation, you can mount the uploads folder at /uploads, otherwise perhaps in /uploads/import.

You may want to look at https://github.com/LycheeOrg/Lychee-Docker/blob/master/docker-compose.yml#L33 for inspiration.

**Comment by andy47** [comment]
Sorry, I probably didn't explain myself clearly. I have an existing library of photos (about 6,000) on my NAS. I would like to present these with Lychee but don't want to duplicate the files by importing them and storing them on another server. I've mapped the uploads folder for new photos but can I index and view existing photo files without importing them?

**Comment by d7415** [comment]
> can I index and view existing photo files without importing them?

No, but you can import them using symlinks to avoid duplicating the full size images.
