### ISSUE TITLE
Docker setup with php 8.1

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee-Docker#110]
Nice to haves: 
* php8.1-alpine as base image so that the image would be LOT smaller
* nginx-alpine as a optional image

**Comment by ildyria** [comment]
Also php 8.1 gives a way more future proof approach :)

**Comment by d7415** [comment]
- Yes, 8.1 support (and Lychee 4.40 support) is planned.
- At some point, an alpine image might prove doable. There was a reason the debian image was preferred early on, and I can't remember what that was. For now I don't plan to move - I'm not against it, but it's likely to be a lot of effort.
- The official php alpine images are not suitable. They either run the CLI php (no use here) or just the fpm. For support reasons, the official Lychee image will include something in front of php-fpm.

**Comment by haivala** [comment]
Why would it be lot of effort? basically change apt to apk?

For support reasons? It would be easier to know the culprit if the containers are separate.

**Comment by d7415** [comment]
> For support reasons? It would be easier to know the culprit if the containers are separate.

In theory yes. In practice, no. It may help debugging but it would result in many more reports in the first place.

**Comment by haivala** [comment]
> > For support reasons? It would be easier to know the culprit if the containers are separate.
> 
> In theory yes. In practice, no. It may help debugging but it would result in many more reports in the first place.

I think this is thing of the past and it is [recommended to have one container for one service](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container). what it needs is decent defaults and mounts.

**Comment by d7415** [comment]
- Stack Exchange is never a good source
- I'm not denying that point. However from experience our users mostly want "tied up in a bow"
- Drastically changing the structure of the image is poor form anyway without lots of notice
- I have no plans to maintain multiple variations

It's very easy to come into a project and say "you should be doing it this way!". Your way may even be the "best" way (so far as there is such a thing), but it may not suit that project. And you are not the one responsible for supporting it.

**Comment by haivala** [comment]
You don't need to get defensive. 

Arguing what is good source is not necessary as it has the things to consider. I'm just hoping my suggestions are considered when new container is built. I didn't say you would need to maintain multiple variations. Drastic changes need to be done anyways so this is good point to check everything and make it even more future proof.

You do your way and thanks for your time!

**Comment by haivala** [comment]
I made this working setup: https://github.com/EntropyRy/Lychee-Docker

**Comment by haivala** [comment]
Any thoughts about my implementation?

**Comment by d7415** [comment]
> Any thoughts about my implementation?

That is *very* messy. It may work fine for users trying to follow your exact setup, but has a lot of moving parts and aside from the name and instructions isn't Lychee-specific.

Debian Bookworm has finished its PHP 8.1 transition, and this image now supports Lychee 4.4.0, so I'm going to close this now.

**Comment by haivala** [comment]
I don't get it how it is messy?

It has everything that is needed to run Lychee so it is Lychee-specific. The code with pics are just mounted inside the docker container that has tools to run it and the output is only configurable port.  You could throw in any lychee install dir and it's database and it would work (just sync the db creds)

Did you try it? I would imagine it would be great for development too.
