### ISSUE TITLE
Is the docker version in docker hub Lycheeorg/Lychee obsolete ?

### ISSUE THREAD

**Issue by ariznaf** [LycheeOrg/Lychee-Docker#113]
I had lychee 4.3.6 running in a docker in a QNAP NAS.

I have read about the new 4.4 version.
So I deleted the docker container and image I had and recreated a new one from the docker hub Lycheeorg/Lychee source.

Configured the /conf,/syme and /uploads to point to the host directories and lauched it.

But once launched it says it is version 4.3.6.
I had expected the new version and database being upgraded to the new version.

Is the docker version in docker hub obsolete?
How can I get a docker container  with the updated lychee version?

Thanks for your work.

**Comment by d7415** [comment]
It's not obsolete, but is pending.

My current options are:

- Do everything from scratch
- Use php8 Debian packages from a (sort of) 3rd-party. You can look at the [php8](https://github.com/LycheeOrg/Lychee-Docker/tree/php8) branch if interested. This will require dropping armv6 support though.
- Wait for the php8.1 transition in Debian Testing.

As the user-facing [changes](https://lycheeorg.github.io/docs/releases.html#v440) in 4.4.0 are relatively minor I'm waiting for now.

**Comment by ariznaf** [comment]
Ah, Ok, so it is just a matter of not having upgraded the docker distribution yet, thank you.
I had believed I had something wrong in my install or that the the docker had been moved to other place.

I will wait, then, and if the major changes is just using php8 it is a technical upgrade, no hurries, then.

My system is x86 not arm, I am lucky, there has been lots of packages dropping arm support.

By the way: may I install git in the docker machine too in order to be able to upgrade from the interface instead of upgrading whole docker.
It would be great to upgrade from the interface when there is no major OS changes.

Why is the docker distributed without git and that option of internal upgrading?
I have other packages in docker that let you do that.
Is there some drawback with that?

In QNAP you cannot upgrade the docker install, you need to delete it and recreate it with the host directory links in order to conserve the photos and database.

I would like to create a docker myself, to try install basic debian, php8 and git and lychee in it, but have no experience creating docker images.

**Comment by haivala** [comment]
Does the Qnap run docker-compose? if it does, check out https://github.com/EntropyRy/Lychee-Docker

**Comment by d7415** [comment]
Hi, sorry for the delay.

Firstly, `lycheeorg/lychee:latest` is now at v4.4.0, and the `:dev: tag should follow with the nightly build in a few hours.

You can install git in the container if you wish. Generally Docker containers are upgraded by replacing the image though, so I don't plan to install it by default.

It sounds like QNAP's implementation (or, perhaps more likely, user interface) is poorly designed. There certainly *should* be a way for it to just pull the latest image to upgrade.

If you want to make your own image including git (or any other tools) the easiest way would be to clone this repository and look at the [Dockerfile](https://github.com/LycheeOrg/Lychee-Docker/blob/master/Dockerfile). If you want to start from scratch, that may provide some pointers but is likely far more complicated than you need!
