### ISSUE TITLE
Failed to load resource: the server responded with a status of 504

### ISSUE THREAD

**Issue by tiritibambix** [LycheeOrg/Lychee-Docker#116]
Hello !

I'm having this issue with large photos.
I found an old post mentioning this but can't find the fix (or I cant understand it).

I also found the [default.conf](https://github.com/LycheeOrg/Lychee-Docker/blob/master/default.conf) but I don't know what to do with it.

May a kind soul guide me please ?

**Comment by alex-greet** [comment]
I am seeing a similar issue. With images larger 5mb I am getting the same error. After removing all metadata from the image it uploads just fine.

**Comment by tiritibambix** [comment]
> I am seeing a similar issue. With images larger 5mb I am getting the same error. After removing all metadata (tags created on Windows) from the image it uploads just fine.

Thanks for your input, but it didn't do the trick for me.

**Comment by alex-greet** [comment]
@tiritibambix can you post your diagnostics from the GUI?

**Comment by tiritibambix** [comment]
Just realized I wasn't using the right image.
Sorry for wasting your time, everything works fine.
