### ISSUE TITLE
Startup delay - Docker

### ISSUE THREAD

**Issue by pigate-eu** [LycheeOrg/Lychee-Docker#126]
Hi,

I have installed lychee in a docker. I have entered about 80000 photos in various albums totaling 300 albums. Sometimes I close this docker-container and open it whenever I need it. The issue is that when I open docker it takes about 30 minutes for lychee to be available as the "find... chown -R lychee:lychee" command is run. Is there a way to make it open directly without delay? I have put "STARTUP_DELAY=0" in my .sh file that I built docker with but saw no difference.

Thank you

**Comment by d7415** [comment]
That find command is an optimisation to speed things up - it really shouldn't take 30 minutes. Is that running on a very slow filesystem?

`STARTUP_DELAY` is an artificial delay to allow slow dependencies (mostly external DB servers) time to start, and defaults to 0, so won't help you here.

**Comment by d7415** [comment]
It may also be slow if those files have the wrong permissions, but in that case it is required.

**Comment by pigate-eu** [comment]
I have the container in a virtual machine, maybe it takes longer to finsish startup find...chmod due to a slow system. However, I have run the chmod command which gave me in Diagnostics that there are many files with wrong permissions and additionally I run "chown -R lychee:lychee" (inside of the container, docker exec -it...). Now on Diagnostics it gives me is for dropbox key warning (which I ignore). So while I have run all these commands and I have not added new albums or photos with each restart of the system and the container, the find...chmod command runs and takes from 20 minutes to 40 minutes to complete. I don't have mysql database, I run it with sqlite.
What should I do so that it doesn't take so long? Is there any way to keep the correct permissions permanently?

**Comment by d7415** [comment]
I've changed the permissions in the entrypoint script to match the diagnostics - They weren't causing a problem, but it'll stop the errors.

The container checks the permissions on each start because pictures are often mounted outside of the container, where permissions can break easily. The find really shouldn't take that long, especially after the first run, once the permissions are set.

**Comment by pigate-eu** [comment]
Finally, I uncomment all lines starting from find command on entrypoint.sh and I restart the container. The problem solved with this way.
