### ISSUE TITLE
Lychee-Docker + Nginx SSL termination

### ISSUE THREAD

**Issue by rc042** [LycheeOrg/Lychee-Docker#131]
Hi,

This is not a bug, however, I'm stuck and I don't know how to do.

I have Lychee-Docker which works fine locally (eg. http://10.0.0.1). 

I have a Nginx on another location who hosts the certificates (let's say that its IP is 172.16.0.1) and I want to proxy pass the traffic from this reverse proxy to Lychee-Docker : The configuration seems fine BUT I have a "419" error (csrf issue?)...

The browser console:
```
Request URL: https://my.domain/api/Albums::get
Request Method: POST
Status Code: 419 
Remote Address: XX.XX.XX.XX:443
Referrer Policy: no-referrer
```

The Lychee-Docker's log:

```
lychee       | XX.XX.XX.XX - - [27/Dec/2022:09:06:14 +0000] "POST /api/Session::init HTTP/1.0" 200 23564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "XX.XX.XX.YY"
lychee       | XX.XX.XX.XX - - [27/Dec/2022:09:06:14 +0000] "POST /api/Albums::get HTTP/1.0" 419 80 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "XX.XX.XX.YY"
```

I also tried to add SSL on Lychee (https://github.com/LycheeOrg/Lychee-Docker/issues/127) but it's the same situation...

Do you have some feedbacks to help me in the resolution?

Thanks!

**Comment by rc042** [comment]
Just for the test (THIS IS NOT RECOMMENDED!): I disable the CSRF protection on Laravel and it works, file edited `/var/www/html/Lychee/app/Http/Middleware/VerifyCsrfToken.php`:

```
	protected $except = [
		// entry points...
	/*	'/php/index.php',
		'/api/Session::init',
	*/
		'*',
	];
```

I do not prefer use Lychee with  the CSRF protection disabled so I will continu to investigate :)

**Comment by d7415** [comment]
I think you need to set [`TRUSTED_PROXIES`](https://github.com/LycheeOrg/Lychee/blob/master/.env.example#L79-L84). Also make sure your [`APP_URL`](https://github.com/LycheeOrg/Lychee/blob/master/.env.example#L5) is set correctly.

**Comment by rc042** [comment]
Hello @d7415 ! I have these settings configured and it doe not work... Here the environment's variables:

```
[...]
      - APP_URL=https://my.domain
      - TRUSTED_PROXIES=*
```

I do a wilcard for the proxy as the example below https://github.com/LycheeOrg/Lychee/blob/master/.env.example

**Comment by ildyria** [comment]
Old but nonetheless the solution is:
- set up `APP_URL` as you did
- set up `TRUSTED_PROXIES`
- **set up proper _proto https_ forwarding to Lychee in your Nginx reverse proxy**
- possibly set up `APP_FORCE_HTTPS` to `true`
