### ISSUE TITLE
unable to load css or create admin account

### ISSUE THREAD

**Issue by mbc3** [LycheeOrg/Lychee-Docker#142]
I started Lychee via podman (running podman-compose).
 
Visiting the service gives me this:

![lychee-install](https://user-images.githubusercontent.com/48695249/219803319-bfbcf546-c114-4bcc-b222-540bb416cd79.png)

And I am unable to create an account.

I suspect what's going on has something to do with file permissions, as it looks like the CSS isn't being loaded.

My user has read/write permissions on the `conf` directory.
`Sym` and `uploads` directory is owned by user/group `100999`

**Attempted fixes:**

I extended read/write permissions to my user with `setfacl`, but it still didn't work.

I added `TRUSTED_PROXIES=*`

to my docker-compose file, as I'm running this on a reverse proxy via nginx and https.

I added the `:z` volume mount flag for SELinux in my docker-compose file for all my volumes, like so:

volumes:
- /opt/lychee/conf:/conf:z
- /opt/lychee/uploads:/uploads:z
- /opt/lychee/sym:/sym:z

I switched to the :dev branch release, but that didn't fix my issue, either.

**Comment by ildyria** [comment]
My guess is that you are accessing the website in HTTP and that the CSS resources are served in HTTP.
Can you check at the console / Network connection tab in your browser whether that's the case.

We now have a `.env` setting to enforce HTTPS, this should hopefully resolve this issue.

**Comment by mbc3** [comment]
Thank you so much! This was precisely the case. In case anyone else needs more explicit instructions, I resolved this issue by setting:

APP_FORCE_HTTPS=true
APP_URL=https://localhost

in my docker-compose file. Lychee is running flawlessly now.
