### ISSUE TITLE
Request for option to skip Set Permissions

### ISSUE THREAD

**Issue by sigulete1** [LycheeOrg/Lychee-Docker#163]
I'm using this container to implement Lychee. And everything works well except one thing.

My photos are stored in a S3 bucket where `/uploads` is pointing to. Every time the application starts, and it goes through the initialisation routine from `entrypoint.sh`, the section related to Set Permissions takes **4 to 5 hours** to complete.

This is a limitation with S3 storage, going through files (`find /uploads`) is painfully slow. So I was wondering if it is possible to add an environment variable switching this section `on/off` as needed. Something like:

`podman .... -e PERMISSION_CHECK=no ...`

**Comment by ildyria** [comment]
@d7415  ?

**Comment by ildyria** [comment]
BTW, that would be a nice addition to our documentation: how to setup Lychee docker with S3.
https://github.com/LycheeOrg/LycheeOrg.github.io
If you could describe your setup here:
https://github.com/LycheeOrg/LycheeOrg.github.io/blob/master/docs/advanced-setups.md
that would be amazing.

**Comment by sigulete1** [comment]
Thanks !!
