### ISSUE TITLE
DB Error on upgrade

### ISSUE THREAD

**Issue by wildeyedskies** [LycheeOrg/Lychee-Docker#173]
After updating my lychee instance is getting the following error

```lychee_db  | 2023-12-27 16:14:03 10 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').```

DB is mariadb

**Comment by ildyria** [comment]
I am 100% sure this is not the correct Lychee you are talking about.

**Comment by ildyria** [comment]
I may have been a bit too quick to trigger that one.

I get the feeling this might be because your DB engine version is too old.

**Comment by wildeyedskies** [comment]
It's mariadb 10, should I upgrade that?

**Comment by wildeyedskies** [comment]
Upgraded to mariadb 11 and the issue seems to be fixed
