### ISSUE TITLE
brand new site can't see images

### ISSUE THREAD

**Issue by mlapaglia** [LycheeOrg/Lychee-Docker#176]
running `docker run -p 80 lycheeorg/lychee` creates a site that images can't be viewed after uploading them, looks like it's trying to get images from `localhost`
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/ccaa6151-59d8-4511-9e56-1ff39357d3bc)
is there any documentation for how to get it up and running successfully?

**Comment by MikeTheTux** [comment]
You need to set `APP_URL` env variable to the IP Address

**Comment by mlapaglia** [comment]
what port is https on? i tried using 443 but it doesn't respond.
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/5ac536a4-b3f7-44bc-9b19-ec4600efcc3c)

**Comment by ildyria** [comment]
it does respond, but it all the queries you are making afterwards are blocked by the CSP. That is because you are trying to fetch http on the data.
You need to set you APP_URL with the https prefix.

**Comment by mlapaglia** [comment]
ok switched it to the 443, the site isn't responding to 443 it still works on 80 though
```
docker run -d
  -e 'APP_URL'='https://192.168.1.164:4880/'
  -p '4879:80/tcp'
  -p '4880:443/tcp'```

![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/d45f0bbe-1b0a-4e38-b7cb-d902090cd472)

![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/0076ae66-25d0-410c-a9a2-9e7bb20a25cc)

**Comment by ildyria** [comment]
```
docker run -d
  -e 'APP_URL'='https://192.168.1.164'
  -p '4879:80/tcp'
```

**Comment by ildyria** [comment]
you can't use https without setting a certificate or using a reverse proxy.
Our docker image only opens port 80.

If you use a reverse proxy which takes care of https (and the certificate) and redirect then traffic to 80, then you will need to set your APP_URL to https.

**Comment by MikeTheTux** [comment]
You can have a look at #175

**Comment by mlapaglia** [comment]
Ok here is my reverse proxy settings:
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/cce0963c-8721-46a4-afbd-fda7329d75e0)

APP_URL is now https://192.168.1.164:4879/

it's still requesting http urls though
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/4184746/d8f74e7e-e666-4cb8-87e5-defc058dc016)

**Comment by MikeTheTux** [comment]
> this just seems like a bunch of workarounds?

I'm also just a user, who struggled with similar problems ...

Did you modify `/etc/nginx/nginx.conf` within the container (`fastcgi_param HTTPS on;`)? I guess this is the missing piece.

**Comment by ildyria** [comment]
> Did you modify /etc/nginx/nginx.conf within the container (fastcgi_param HTTPS on;)? I guess this is the missing piece.

That should not be necessary as long as the reverse proxy is forwarding https headers.

I'll try to improve the description for Apache, but I can't really do much for the nginx one as I don't have knowledge there.

**Comment by mlapaglia** [comment]
I can lend a hand if you can show me how to record the headers being forwarded. is there something special about lychee that makes it work different than many other docker containers i forward the same way to? could the APP_URL be omitted and the site serve up content to whatever requests it?

**Comment by ildyria** [comment]
FYI:
https://github.com/LycheeOrg/Lychee/pull/2182
https://github.com/LycheeOrg/Lychee/pull/2181

**Comment by ildyria** [comment]
Should be resolved with latest builds.
