### ISSUE TITLE
Any uploaded or 'php artisisan lychee:sync /path/' image is blank and unviewable.

### ISSUE THREAD

**Issue by ghxstxch** [LycheeOrg/Lychee-Docker#182]
Hi there! 

I'm unsure if I'm doing something that's very simple wrong. I had initially updated from a perfectly working version 4.0.3 (I think. The number in the middle I'm unsure about) directly to the latest available version (Lychee 5.1.1). This resulted in all my images looking like this, seemingly broken, using the unsorted folder as an example.
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/107282306/9f4e1fae-932c-4912-8a47-607a79cd6521)

The originals can be viewed perfectly fine (although it keeps pointing towards localhost instead of the IP address or the webpage I pointed it to, unsure how to change that too), it just seems to refuse to display them in 'Gallery' mode. 

I've also attempted to just start from scratch and wiped everything and performed  'php artisisan lychee:sync /path/' for the directory that is storing these images. The same exact issue occurs. Logs will be attached below as I cannot seem to download them. What am I doing wrong?! Please let me know what other info I can provide. 

![image](https://github.com/LycheeOrg/Lychee-Docker/assets/107282306/d4e001f6-4d1b-4b5e-87f5-825e2934be63)
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/107282306/1f1bcf95-6c7f-47bb-9bf9-de9d17df58d3)

**Comment by ildyria** [comment]
> I'm unsure if I'm doing something that's very simple wrong. I had initially updated from a perfectly working version 4.0.3 (I think. The number in the middle I'm unsure about) directly to the latest available version (Lychee 5.1.1). This resulted in all my images looking like this, seemingly broken, using the unsorted folder as an example.

I strongly suggest you have a look at the diagnostics. Those broken image are most likely explained there.
Please provide that data to us.

**Comment by ghxstxch** [comment]
> > I'm unsure if I'm doing something that's very simple wrong. I had initially updated from a perfectly working version 4.0.3 (I think. The number in the middle I'm unsure about) directly to the latest available version (Lychee 5.1.1). This resulted in all my images looking like this, seemingly broken, using the unsorted folder as an example.
> 
> I strongly suggest you have a look at the diagnostics. Those broken image are most likely explained there. Please provide that data to us.

Here is what is in diagnostics - seems like its tied to my other question on why everything comes up as localhost instead of it's IP.

```
    Diagnostics
    -----------
        Warning: Dropbox import not working. dropbox_key is empty.
        Warning: APP_URL is still set to default, this will break access to all your images
                 and assets if you are using Lychee behind a sub-domain.
        Error: APP_URL (http://lo*****st) does not match the current url (http://10.*******0:90).
               This will break WebAuthn authentication.
        Error: APP_URL (http://lo*****st) does not match the current url (http://10.*******0:90).
               This will prevent images from being properly displayed.
        Info: Latest version of PHP is 8.3
        Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
        Warning: git (software) is not available.
     

    System Information
    ------------------
        Lychee Version (git):                    ?? (1e3b000) -- Could not compare.
        DB Version:                              5.1.1
        
        composer install:                        --no-dev
        APP_ENV:                                 production
        APP_DEBUG:                               false
        APP_URL:                                 default
        APP_DIR:                                 default
        LOG_VIEWER_ENABLED:                      true
        LIVEWIRE_ENABLED:                        true
        
        System:                                  Linux
        PHP Version:                             8.2.7
        PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
        Timezone:                                UTC
        Max uploaded file size:                  100M
        Max post size:                           100M
        Livewire chunk size:                     12.00 MB
        Max execution time:                      3600
        MySQL Version:                           10.11.6-MariaDB-1:10.11.6+maria~ubu2204
        
        exec() Available:                        yes
        Imagick Available:                       1
        Imagick Enabled:                         1
        Imagick Version:                         1691
        GD Version:                              2.3.3
        Number of foreign key:                   12 found.
     

    Config Information
    ------------------
        version:                                 050101
        check_for_updates:                       0
        sorting_photos_col:                      taken_at
        sorting_photos_order:                    ASC
        sorting_albums_col:                      max_taken_at
        sorting_albums_order:                    ASC
        imagick:                                 1
        skip_duplicates:                         0
        small_max_width:                         0
        small_max_height:                        360
        medium_max_width:                        1920
        medium_max_height:                       1080
        lang:                                    en
        image_overlay_type:                      desc
        default_license:                         none
        compression_quality:                     90
        grants_full_photo_access:                1
        delete_imported:                         0
        mod_frame_enabled:                       1
        mod_frame_refresh:                       30
        thumb_2x:                                1
        small_2x:                                1
        medium_2x:                               1
        landing_page_enable:                     0
        site_owner:                              Thomas and Katelyn Young
        landing_title:                           John Smith
        landing_subtitle:                        Cats, Dogs & Humans Photography
        sm_facebook_url:                         https://www.facebook.com/JohnSmith
        sm_flickr_url:                           https://www.flickr.com/JohnSmith
        sm_twitter_url:                          https://www.twitter.com/JohnSmith
        sm_instagram_url:                        https://instagram.com/JohnSmith
        sm_youtube_url:                          https://www.youtube.com/JohnSmith
        landing_background:                      dist/cat.webp
        site_title:                              Thomas and Katelyn's Wedding Photos
        footer_show_copyright:                   1
        site_copyright_begin:                    2019
        site_copyright_end:                      2024
        footer_additional_text:                  
        footer_show_social_media:                0
        search_public:                           0
        SL_enable:                               0
        SL_for_admin:                            0
        recent_age:                              1
        grants_download:                         0
        photos_wraparound:                       1
        map_display:                             1
        zip64:                                   1
        map_display_public:                      1
        map_provider:                            OpenStreetMap.org
        force_32bit_ids:                         0
        map_include_subalbums:                   0
        update_check_every_days:                 3
        has_exiftool:                            1
        share_button_visible:                    0
        import_via_symlink:                      0
        has_ffmpeg:                              1
        location_decoding:                       1
        location_decoding_timeout:               30
        location_show:                           1
        location_show_public:                    0
        rss_enable:                              0
        rss_recent_days:                         7
        rss_max_items:                           100
        prefer_available_xmp_metadata:           0
        editor_enabled:                          1
        lossless_optimization:                   0
        swipe_tolerance_x:                       150
        swipe_tolerance_y:                       250
        local_takestamp_video_formats:           .avi|.mov
        log_max_num_line:                        1000
        unlock_password_photos_with_url_param:   0
        nsfw_visible:                            1
        nsfw_blur:                               0
        nsfw_warning:                            0
        nsfw_warning_admin:                      0
        nsfw_banner_override:                    
        map_display_direction:                   1
        album_subtitle_type:                     oldstyle
        upload_processing_limit:                 4
        new_photos_notification:                 0
        legacy_id_redirection:                   1
        zip_deflate_level:                       6
        SA_enabled:                              1
        default_album_protection:                1
        album_decoration:                        layers
        album_decoration_orientation:            row
        allow_username_change:                   1
        auto_fix_orientation:                    1
        use_job_queues:                          0
        random_album_id:                         starred
        use_last_modified_date_when_no_exif_date: 0
        ffmpeg_path:                             /usr/bin/ffmpeg
        ffprobe_path:                            /usr/bin/ffprobe
        layout:                                  justified
        date_format_photo_thumb:                 M j, Y, g:i:s A e
        date_format_photo_overlay:               M j, Y, g:i:s A e
        date_format_sidebar_uploaded:            M j, Y, g:i:s A e
        date_format_sidebar_taken_at:            M j, Y, g:i:s A e
        date_format_hero_min_max:                F Y
        date_format_hero_created_at:             M j, Y, g:i:s A T
        date_format_album_thumb:                 M Y
        upload_chunk_size:                       0
        nsfw_banner_blur_backdrop:               0
        search_pagination_limit:                 1000
        search_minimum_length_required:          4
        photo_layout_justified_row_height:       320
        photo_layout_masonry_column_width:       300
        photo_layout_grid_column_width:          250
        photo_layout_square_column_width:        200
        photo_layout_gap:                        12
        display_thumb_album_overlay:             always
        display_thumb_photo_overlay:             hover
        default_album_thumb_aspect_ratio:        1/1
        use_album_compact_header:                0
        login_button_position:                   left
        back_button_enabled:                     0
        back_button_text:                        Return to Home
        back_button_url:                         /
     

```

**Comment by ildyria** [comment]
Can you edit your `.env` and fix that APP_URL value to the ip + port in question ?

**Comment by ghxstxch** [comment]
> Can you edit your `.env` and fix that APP_URL value to the ip + port in question ?

This allows me to access it via the IP I put in, BUT it does not seem to respect the environment variable I set for my reverse proxy (nginx proxy manager). I am able to access it and don't get the "Lychee was misconfigured" message, but I also, same as before, am not able to view images. Here are my current env variables. 

```

      - PHP_TZ=America/Chicago
      - TIMEZONE=America/Chicago
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_FORCE_HTTPS=false
      #- APP_DEBUG=true
      - APP_URL=http://10.0.###.###:90
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=###########
      - STARTUP_DELAY=30
      - TRUSTED_PROXIES=192.168.69.###
```

Additionally - some things are also acting a bit funky, I cannot move photos to other albums, as this pops up and does not allow itself to be clicked. Seems like it's trying to generate a thumbnail for the album but it fails and breaks the ability to move pictues doing so? 

**
![image](https://github.com/LycheeOrg/Lychee-Docker/assets/107282306/8d773893-e9f2-4359-afc6-6b019bd0f510)
**

**Comment by Baltimorepc** [comment]
i have the same question. Also how to get the landing background to work i have tried everything i have found in the forums and nothing works. i even tried dropping the pic in the config folder where i know it sees as its writing stuff to it but the log in lychee says the location isn't found so weird i an on the new version 5.5.1

**Comment by ildyria** [comment]
> dropping the pic in the config folder

only the files in `public/` are accessible.

The landing background is just a url. If you right click on one of the picture in your photo view, and copy the url, that is the one you can use.

**Comment by Baltimorepc** [comment]
i tried that it didnt work i even tried moving the uploads/pictures folder to my public folder and it still wont work just shows broken thumbnail. i would be happy if i could just keep it black but if i leave it blank it still shows a broken thumbnail

**Comment by ildyria** [comment]
Okay, is your question about sync or about landing background ? because that is very unclear to me.

**Comment by Baltimorepc** [comment]
its the landing page as i cant get any other pic to work but the default one i tried url and the added volume for uploads nether would work. IF i can just make the landing page background jut blank/black. As i tried to leave the option blank so it wuld just be a black background but still shows a broken thumbnail

**Comment by Baltimorepc** [comment]
actually i just tried it again and it worked. i did see that it did a lychee update so i am guessing maybe that fixed it. Thank you for your replies and assistance. I do have a couple other questions. Is there a way to make the wording bigger on the landing page and or change color and slow it down a little when you first go as in how it fads in. Can i slow it down a little some how?  . and move the Gallery or login link to the middle as on a phone it gets covered by the tittle and i cant shorten it as its for my wedding. Im sorry for all the questions and i appreciate all the feedback. I know use are busy and don't have time but if you do i do appreciate all your help so far.

**Comment by Baltimorepc** [comment]
also i noticed there is no login button showing on the Landing page. Just a gallery button at the top right that get covered while checking on the phone

**Comment by ildyria** [comment]
>  I do have a couple other questions.

I am sorry but this is not how this works.

1. this is the docker repository for Lychee. See https://github.com/LycheeOrg/Lychee for the original repository.
2. I am doing this on my free time and mostly without any support. I am not taking personalized requests.
3. There is a user.css in public/dist (if I remember correctly) which should allow you customize some of those.

I will have to close this question unfortunately.

**Comment by ghxstxch** [comment]
Thank you - my sincere apologies for not closing this thread myself. I haven't touched my install outside of updates, and it's been rock solid. Thank you for doing what you do @ildyria

**Comment by Baltimorepc** [comment]
sorry
