### ISSUE TITLE
Lychee empty after rough update

### ISSUE THREAD

**Issue by ih8ms** [LycheeOrg/Lychee-Docker#206]
Hi everyone,

not sure this is a Docker or a Lychee issue, but as I run it in Docker, I thought I'd file it here first.

I updated from v4.13.0 to v5.5.1. As I haven't found any particular instructions, I thought the update could be done in place. First, I got that "if you can read this, your Lychee is misconfigured" message which I could fix by updating my nginx configuration (running nginx as reverse proxy).

I can log into Lychee with my original user now, but Lychee itself is completely empty. No galleries, no content, no nothing.

Please advise

**Comment by ildyria** [comment]
Can you give us a view of the Diagnostics ? 
You can probably access them by using `/Diagnostics` in the URL.
Also I would suggest to check the console logs of your browser and the network log to see if there is not a 404 laying around.

Finally, in your case I would also recommend to go to your `.env` and set `LIVEWIRE_ENABLED=false` to get back to the v4 interface. v6 is coming soon :tm: and the full v5 front-end is going to trash.

Read more here:
- https://lycheeorg.github.io/2024-06-29-future-of-lychee/
- https://lycheeorg.github.io/2024-06-25-performance-problems/

**Comment by ih8ms** [comment]
Allright, so `LIVEWIRE_ENABLED=false` fixed the issue for me. I had it seen as `ENABLE_LIVEWIRE=false` before, which obviously didn't work.
