### ISSUE TITLE
Renaming this repo/image

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-Docker#38]
Lychee v4 has been released as `Lychee`, so it may make sense to rename this repo to `Lychee-Docker` and/or the image to `Lychee`.

 - Renaming the repo should have minimal effect as GitHub will redirect from the old URLs.
 - The image name might be better pushed to both names, unless Docker Hub has a similar mechanism.

Leaving this open for any other considerations. I don't see any rush.

**Comment by roblandry** [comment]
Is say this is something worth looking into. DockerHub doesn't have a built in mechanism to migrate to a new name that I'm aware. Is day of we were to want to transition the name of the image, it should be a slow process to allow users to migrate. 
1. Create a new image and push it. While still pushing to larval docker.
2. Post notices about the migration. Possibly in the docker entrypoint as a notice also. 
3. Wait some determined period of time. While still pushing to both. 
4. Complete migration. Depreciate the old.

**Comment by d7415** [comment]
`deploy.sh` now uses the `lychee` Docker Hub repo for `:testing` and both repos for `:dev` and `:tags`.

I've drafted some changed documentation but without the notices yet.

**Comment by ildyria** [comment]
:stuck_out_tongue:

**Comment by d7415** [comment]
> I think this is ... no longer needed :)

I can revert it back to lycheeorg/lychee-laravel if you like? :P
