### ISSUE TITLE
Docker Image for Lychee 4.0.x releases

### ISSUE THREAD

**Issue by manniL** [LycheeOrg/Lychee-Docker#40]
Hey all 👋🏻

I'm wondering if we could get some tagged released (and a bumped latest tag) for the new patch releases of Lychee, (latest is https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.3).

**Comment by d7415** [comment]
Yeah. That's on my list. I'd been meaning to talking to @roblandry about the current version numbering.

On my longer-term list is trying to trigger a docker build when Lychee changes. I should probably make a tracking issue for that.

**Comment by d7415** [comment]
@roblandry Any objections to matching Docker tags to Lychee versions now that v4 is out? Maybe with e.g. 4.0.3-1 if the Docker part needs changing between releases?

**Comment by d7415** [comment]
@manniL While you wait, the :dev tag is updated nightly from Lychee master, which is considered stable.

**Comment by manniL** [comment]
> @manniL While you wait, the :dev tag is updated nightly from Lychee master, which is considered stable.

Thanks for the hint ☺️ 
Saw that, but I'll wait for the next stable tag 👍 
I'm not in a hurry 😋

**Comment by roblandry** [comment]
I honestly believe the version of the docker image should retain its own version, but if the consensus is to match versions, that's fine. As it stands, deploy.sh should be updated to reflect the actual lychee version as apposed to the commit hash. But in the docker logs it displays the cloned lychee version (the git commit hash).

**Comment by roblandry** [comment]
We should probably find some github action or ci to auto tag a new docker image when a new lychee version is released. That way it would no longer be manual. But this is also why there is a dev tag, to keep up with the latest lychee version.

**Comment by d7415** [comment]
I agree it makes sense to track L-L-Docker changes separately. I think I'd propose tracking LLD's GitHub releases on the existing version scheme, but tagging docker images with the Lychee version based on Lychee releases - from my experience, that's what people expect to see there

Does that fit with your view?

I agree with the auto build on a new Lychee tag. That's already on my todo list, but feel free to beat me to it!

**Comment by d7415** [comment]
> deploy.sh should be updated to reflect the actual lychee version as apposed to the commit hash

Just re-read this. For tags? So that it pushes to e.g. 'Lychee-Laravel:v4.0.3" instead of L-L-D's version? deploy.sh doesn't seem to use the commit hash.

**Comment by roblandry** [comment]
Correct, i mispoke, entrypoint.sh is what i intended to type.
```
$ docker logs lychee-laravel -f

-------------------------------------
  _               _                
 | |   _   _  ___| |__   ___  ___  
 | |  | | | |/ __|  _ \ / _ \/ _ \ 
 | |__| |_| | (__| | | |  __/  __/ 
 |_____\__, |\___|_| |_|\___|\___| 
 | |   |___/ _ __ __ ___   _____| |
 | |   / _' | '__/ _' \ \ / / _ \ |
 | |__| (_| | | | (_| |\ V /  __/ |
 |_____\__,_|_|  \__,_| \_/ \___|_|

-------------------------------------
Latest Commit: bae5f2b
https://github.com/LycheeOrg/Lychee-Laravel/commit/bae5f2bbea823f5b0bfc154464dbf16e86ddb7db
-------------------------------------
**** Make sure the /conf and /uploads folders exist ****
```

**Comment by d7415** [comment]
> Correct, i mispoke, entrypoint.sh is what i intended to type.

That shouldn't be hard. I'll look tomorrow with the above and try to PR it.

**Comment by d7415** [comment]
> That shouldn't be hard. I'll look tomorrow with the above and try to PR it.

#51

**Comment by d7415** [comment]
@manniL v4.0.5 has been pushed to Docker!
Notes:
- We're currently migrating to https://hub.docker.com/r/lycheeorg/lychee though we'll push to both for a while yet.
- sqlite is used by default and the UTC timezone, but if you've specified these as variables (as in the example) it won't effect you.
- There's also redis support and a volume for the Lychee symlinks feature.
