### ISSUE TITLE
Add support for docker secrets

### ISSUE THREAD

**Issue by berndderidder** [LycheeOrg/Lychee-Docker#62]
It would be great to have support for [docker secrets](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images).

Looking at the available environment variables I think these should be added:
* `DB_PASSWORD_FILE`
* `REDIS_PASSWORD_FILE`
* `MAIL_PASSWORD_FILE`
* `PUSHER_APP_KEY_FILE`
* `PUSHER_APP_SECRET_FILE`

I had a look at `inject.sh` and my initial thought was like this:

```
if [ "$DB_PASSWORD_FILE" != '' ]; then
  value=$(<$DB_PASSWORD_FILE)
  sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${value}|i" /conf/.env
fi
```

I think this should be it?

**Comment by felin-arch** [comment]
I would also welcome this! I dug around to find an alternative but couldn't find one :(
I am happy to create a PR for this one.

Any thoughts on the suggestion from @berndderidder ? I also think that would work.

**Comment by mingan666** [comment]
Are there any plans to implement this enhancement?

**Comment by d7415** [comment]
#149
