### ISSUE TITLE
Photos are DELETED from host and are MISSING in lychee

### ISSUE THREAD

**Issue by unhappy-trooper** [LycheeOrg/Lychee-Docker#66]
Hello,

I setup lychee as docker container, I bind uploads/import path to my pictures and started the container. I did not start the import process as I was just about to tarball my pictures. However starting the container deleted photos from host but the mysql photos tables has or rows and there are no photos in the docker volume.

I was not expecting files to be deleted until I actioned it on the website and I was ready to start the proccess

Please help where these photos could be. Where are they stored in the lychee volume. Uploads big, medium and small are all empty directories.

At the moment I cannot give more detailed description because I am in the middle of a lengthy data recovery!

**Comment by d7415** [comment]
1) Are you using the official Docker image?
2) If so, which tag/version/etc?
3) How are you binding the folder?

I've reread our entrypoint twice and there's nothing that should affect you in this way.
