### ISSUE TITLE
Images for armv7

### ISSUE THREAD

**Issue by astrofrog** [LycheeOrg/Lychee-Docker#68]
I noticed that the :dev image supports amrv7, but this seems to be missing from the stable tags - is this a work in progress, or are there no plans to support stable tags for armv7 going forward?

**Comment by d7415** [comment]
The multiarch deployment on travis started failing for release builds with 32 bit architectures. There's still a test there, so if it fixes itself we'll start pushing stable builds for those platforms again. Until then, the dev tag is the recommended option or you can build your own.

Lychee aims to keep master stable, so this isn't as big a difference as it might be.
