### ISSUE TITLE
Link to example docker-compose.yml is dead

### ISSUE THREAD

**Issue by radek-sprta** [LycheeOrg/Lychee-Docker#73]
As title says, the following link https://hub.docker.com/r/lycheeorg/docker-compose.yml in the readme returns 404.

**Comment by d7415** [comment]
Good spot. That was missed in the migration from the ["real"](https://github.com/LycheeOrg/Lychee-Docker/blob/master/README.md) readme to the Docker Hub one, but is fixed now. Thanks!

**Comment by omichalek** [comment]
The docker-compose.yml link at https://hub.docker.com/r/lycheeorg/lychee is still or again dead

**Comment by ildyria** [comment]
> The docker-compose.yml link at [hub.docker.com/r/lycheeorg/lychee](https://hub.docker.com/r/lycheeorg/lychee) is still or again dead

it's because the markdown processing by hub.docker.com is not creating anchors for h titles `#` `##` etc. :|

**Comment by d7415** [comment]
Fixed
