### ISSUE TITLE
Problems with install and directory/files owners

### ISSUE THREAD

**Issue by ariznaf** [LycheeOrg/Lychee-Docker#75]
I have installed Lychee-Docker in a NAS using docker (QNAP NAS with docker station).

I have created directories for /conf, /sym and /uploads, and mouented the corresponding volumes

The docker install script created the appropiate files and directories (/conf/.env,/uploads/thumb...).

But when I tried to run Lychee for the first time, the install script found problems /sym and /uplodas being not readable/writeable.

I have checked the ownership and /uploads and /sym are owned by lychee:lychee after being created by the docker script, shile /conf is owned by www-data:www-data.

I have changed the ownership of that directories and their subdirs to www-data:www-data, and the lychee install could progress.

Then there was a HTTP:500 page error  then it directed me to the url http://lychee.somedomain/install/env.

I have checked file /conf/.env and ownership was lychee:lychee.
Everything seems to work OK when I changed that to www-data:www-data.

I am not sure if this is a bug in the docker install scripts.

I had previously installed Lychee-Docker without configuring the /conf,/uploads,/sym volume entry points (which creates docker volumes authomatically) and it worked OK.
But now I want to control where that files reside, and seems that the install script has some kind of bug.

**Comment by d7415** [comment]
Which version are you running?

**Comment by ariznaf** [comment]
4.0.7, I have selected latest docker source.

**Comment by d7415** [comment]
Ok. The `/sym` permissions should have been solved in #74, which isn't in a tagged release yet. There is potential issue with `.env` and the installer which I'll have a think about. In the recommended use case the installer isn't required.

`/uploads/` shouldn't be a problem - it's set up in `entrypoint.sh` to be owned by lychee but for the www-data user to have access. I'll see if I can reproduce this - most of my testing is just using default Docker volumes rather than mounts for convenience.

**Comment by ariznaf** [comment]
The problem is that the Lychee install script checks for /uploads directories to see if Lychee has read/write access on it, and I guess that it does it under the www-data user, so it reports that error and does not continue until you fix the ownership, but I am not sure if changing ownership of /uploads  to www-data can be a security break.

**Comment by d7415** [comment]
https://github.com/LycheeOrg/Lychee-Docker/blob/master/entrypoint.sh#L110

**Comment by ariznaf** [comment]
I see, it seems you assign lychee user the ownership and give www-data access to it.

But the install process of Lychee-installer complains about uploads and subdirs not being readable/writable.

I does not happen when you use authomatically created docker volumes for it (at least it did not happened to me).
But when you mount them in a specific directory of the hosting server, the problem arises (at least in my QNAP NAS).

**Comment by ariznaf** [comment]
An update to this problem

When I restart the NAS and the lychee docker container is reinitiated, the /uploads and /sym dirs and the /conf/.env file are again owned by lychee:lychee user, so when I try to connet to the lychee install from the browser, instead of accessing the galleries, the lychee installer is launched again.

I have to sh into the container and change the owner of those dirs and file again.

**Comment by d7415** [comment]
> When I restart the NAS and the lychee docker container is reinitiated, the /uploads and /sym dirs and the /conf/.env file are again owned by lychee:lychee user

Yup. entrypoint is run every time the container starts.

**Comment by ariznaf** [comment]
So I cannot use this docker distribution until these is fixed...

it is strange, as entrypoint seems to get sure www-data has access to the files, but for some strange reason it has not.

May it be due to the filesystem in the host server not being of the expected type?

I suppose that if I configure USER to be www-data instead of lychee it will work, but I don't know if it can introduce security breaks...

**Comment by d7415** [comment]
> May it be due to the filesystem in the host server not being of the expected type?

What is the filesystem on the host?

> I suppose that if I configure USER to be www-data instead of lychee it will work, but I don't know if it can introduce security breaks...

The main thing I can think of is that www-data would have write access to Lychee. Which is more an "if there's a problem in Lychee that could make it worse" IMO. Still not ideal.

**Comment by ariznaf** [comment]
Well, I have installed de docker container in my QNAP NAS.

QNAP seems to distribute a propietary distribution of GNU Linux.

cat /proc/version  displays as:
Linux version 4.14.24-qnap (root@U16BuildServer124) (gcc version 4.9.2 (toolchain config: [gcc-4.9.2 binutils-2.25 glibc-2.21])) #1 SMP Fri Sep 25 01:15:18 CST 

It seems it is a variant of Ubuntu (or at least was in the past, as some versions ago it reported linux version as ubuntu derivative.


It uses an expandable filesystem (a software RAID) and the base devices seem to be formatted using ext4 (as mount reports).

When I use 
stat -f /share/mountpoint/lycheedir

it reports the file system as ext2/ext3.

But I suppose any of the not too old file systems would be appropiate to save the extended attributes needes to control permissions in file systems in nodes, don't they?

But it seems it is not working OK.

Can you reproduce the problem if you mount /uploads, /conf and /sym in directories in the host system instead of using docker volumes?

**Comment by ariznaf** [comment]
Well I have found some interesting things, that I am sure that are related to the problem but do not understand how to correct them and the implications.

If I connect to the docker container and use 

id -u lychee
I receive an id of 1000 (the pid assigned to the user and group in the configuration.

id www-data gives me  33 as user id.

/conf is owned by www-data (UID 33) 
/sym and /uploads are owned by lychee (UID 1000).


When I list owners of the files in the HOST file system i get

/share/lychee/conf is owned by 33 whiche is the UID of the www-data in the docker container and does not exist as a user in the filesystem

/share/lyche/uploads (and sym) are owned by user Irene that is a user of the host system

id -u Irene gives me an UID of 1000 which happens to be the id of lychee in the container.

So it seems that in the host directories are assigned the same UID owner of the container and it happens to be the same of a user in the host system (which may be a security break).

The problem seems to be that access to /share/lychee/uploads is not granted to user UID 33 
may be due to that user not existing in the host?

**Comment by d7415** [comment]
Ok. Lots there. It looks like you've found the problem. I see 2 potential solutions.

One is to set the group to www-data rather than adding www-data to the lychee group. I'll have a think, but I'm not immediately seeing downsides.

The other is, as you said, go back to "normal" docker volumes. The docker volumes are browsable (i.e. are just directories) so will have all the data, so that backup solution should be fine.

**Comment by ariznaf** [comment]
Ok.

I let you think about the best solution.

At the moment I am using docker voumes and I have configured backups to backup the docker volumes. May be it is most appropiate that storing config and content of containers in places accesible to other services of the NAS and with permisions set to unknown users of the NAS host.

I don't understand well why it works when you use a docker volume, as if I look for UID of the owner of files under the _data direcotories in the volumes they are exactly the same, 33 and 1000 and files owned by UID 1000 ara identified as belonging to the same user (Irene) and unknown group (1000).

But it works OK.

**Comment by d7415** [comment]
Unable to reproduce. I created and rebooted fine. For reference:

```sh
mkdir -p /tmp/Lycheetmp/conf /tmp/Lycheetmp/uploads /tmp/Lycheetmp/sym
docker run --name=lychee -e DB_CONNECTION=sqlite -p 127.0.0.1:80:80 --mount type=bind,source=/tmp/Lycheetmp/conf,dst=/conf --mount type=bind,source=/tmp/Lycheetmp/uploads,dst=/uploads --mount type=bind,source=/tmp/Lycheetmp/sym,dst=/sym lycheeorg/lychee:v4.0.7
```

**Comment by juanlufont** [comment]
I am experiencing the problem described by @ariznaf, also in a QNAP NAS. 

The test suggested by @d7415 does work on my local machine, so I really suspect the root of the problem is the QNAP firmware and the "weird" way it handles permissions and ownership.
