### ISSUE TITLE
"Personalize your CSS" is not persistent on Docker installs

### ISSUE THREAD

**Issue by verahawk** [LycheeOrg/Lychee-Docker#77]
Steps to reproduce:

1. Spin up Lychee container.
2. As an admin user add some content to "Personalize your CSS".
3. Restart Lychee container.
4. Any CSS modifications are gone.

What I think is going on: custom CSS is stored in `public/dist/user.css` and this file isn't mounted outside of the container (or in any docker volume), so after the restart it's gone. A possible solution would be to move it to /conf directory on docker installs.

**Comment by d7415** [comment]
Good spot. As a temporary measure you can manually mount the file outside the container, but I'll look at doing that properly soon - Hopefully tonight or tomorrow.

**Comment by d7415** [comment]
This fix will be in the `:dev` tag imminently, versioned tags with the next Lychee release.

**Comment by verahawk** [comment]
Can confirm it's working. Thank you for such fast response :)
