### ISSUE TITLE
Lychee configuration broken after running from modified docker image

### ISSUE THREAD

**Issue by shrx** [LycheeOrg/Lychee-Docker#83]
Steps to reproduce:

1. Download lycheeorg/lychee:latest (tested with 4.0.7)
2. Run lychee with `sudo docker run --name=lychee -p 80:80 lycheeorg/lychee`
3. In the web interface set up the admin account and password and change some settings
4. Stop the docker image and commit changes with `sudo docker commit [lychee_container_ID] shrx/lychee`
5. Start the modified image with `sudo docker run --name=lychee-shrx -p 80:80 shrx/lychee`
6. The web interface now redirects to `http://[lychee.domain.tld]/install/env` lychee-installer interface, which complains that all `public/uploads/*` subdirectories are missing.

**Comment by d7415** [comment]
Supposedly it's not supposed to commit any volumes, which is how the image stores pretty much everything. I haven't played with `docker commit`, so I'm afraid you're going to have to figure out what it's changing.

What are you trying to achieve?

**Comment by shrx** [comment]
I want to preserve my settings after I stop and restart the docker image, right now they are reverted to default.

**Comment by d7415** [comment]
Lychee settings are stored in the database. If you don't tell it otherwise it will use an sqlite database stored in the /conf volume. If you want to preserve these settings (and any photos you add) you'll need to mount the same volumes each time, probably using the `-v` argument to `docker run`.
