### ISSUE TITLE
Can't upload video files

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [LycheeOrg/Lychee-Docker#87]
I'm running Lychee in Docker, so I'm filing the issue here.

Whenever I try to upload a video file, the upload itself seems to work, but then it's always stuck in processing and nothing else ever happens.

I have seen nothing useful in the docker log itself and have no idea where else to go for debugging, so I'm kind of stuck with this. Any hints on how to debug this are highly appreciated.

**Comment by ihatemicrosoft-was-already-taken** [comment]
Just for the record: importing video files via file import directly from the server's file system works just fine.

**Comment by ildyria** [comment]
Can you check the diagnostics:
```
Max uploaded file size:          ???M
Max post size:                   ???M
```

**Comment by ihatemicrosoft-was-already-taken** [comment]
```
    Max uploaded file size:          20M
    Max post size:                   100M
```

I have to say that the screen messages were very misleading. It always reported the upload to be done 100% and then was stuck in "Processing" (or whatever the english string is, haven't set mine to english language.

However, I have tested an upload of 15MB, which worked fine. So I guess I have to override the builtin php.ini to allow larger uploads, I guess?

**Comment by ildyria** [comment]
> So I guess I have to override the builtin php.ini to allow larger uploads, I guess?

Yes.

> It always reported the upload to be done 100% and then was stuck in "Processing" (or whatever the english string is, haven't set mine to english language.

This is corrected in the latest version by @kamil4  if I am not wrong.

**Comment by kamil4** [comment]
Yeah, starting with version 4.2.0 there should be a clear diagnostics during upload when this problem occurs.
