### ISSUE TITLE
Cannot upload larger files: upload_max_filesize is not taken from PHP-FPM

### ISSUE THREAD

**Issue by 15Cactus49** [LycheeOrg/Lychee-Docker#90]
### Detailed description of the problem [REQUIRED]
When I run the docker image with sqlite via `docker run -p 92:80 --name lychee lycheeorg/lychee:dev` lychee comes up and I can access through the browser. However, when I try to upload larger files (anything more than 3MB) I get an error saying that the "PHP upload_max_size" file limit is to small. I can check that file limit by running `docker exec lychee php --info | grep max` and indeed, it is set to '2M'. When I try to see which php.ini is being used I see that the php.ini in the cli folder is being used: `docker exec lychee php --info | grep php.ini` results in:

Configuration File (php.ini) Path => /etc/php/7.4/cli
Loaded Configuration File => /etc/php/7.4/cli/php.ini

In the docs it says that by default the `upload_max_size` is set to 200 MB and PHP-FPM is being used. I have changed the config in /etc/php/7.4/fpm/php.ini but that did not have any effect. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Run docker container via `docker run -p 92:80 --name lychee lycheeorg/lychee:dev`
2. Access lychee on localhost:92 , set a password and username and try to upload any file larger than 2MB.

**Screenshots**
![Uploading Screenshot_20210314_153330.png…]()

### Output of the diagnostics  [REQUIRED]
` docker exec lychee php --info | grep php.ini`:
Configuration File (php.ini) Path => /etc/php/7.4/cli
Loaded Configuration File => /etc/php/7.4/cli/php.ini

`docker exec lychee php --info | grep max`
post_max_size => 8M => 8M
upload_max_filesize => 2M => 2M

### Browser and system
Ubuntu 19.10, Firefox 78.

**Comment by d7415** [comment]
For me that worked fine with a 12.4MB image.

As for your diagnostics, if you followed the "Output of the diagnostics" you'd have seen the output there, which is correct.

The Lychee Docker image injects the php settings using the nginx configuration, as detailed in the README (which apparently needs updating, but that's a different issue).

The transfer seems to have broken your screenshot. Could you provide the file that is failing to upload?

**Comment by 15Cactus49** [comment]
Thank you for the quick answer! I am not sure what I did wrong but things no work as expected. I am sorry to have bothered 

There is one thing I do not understand, please let me know if you shed some light on it:
1. Why are the php settings saying that `upload_max_filesize => 2M => 2M `? Is it later overwritten by the settings in the nginx configuration? 

Thanks again for your help!

**Comment by d7415** [comment]
> Thank you for the quick answer! I am not sure what I did wrong but things no work as expected.

Great news!

>     1. Why are the php settings saying that `upload_max_filesize => 2M => 2M `? Is it later overwritten by the settings in the nginx configuration?

Yes. The relevant PHP settings are set in the nginx configuration, not the php.ini, so only take effect when php is called by nginx. That's why the Diagnostics page output (or a phpinfo page) is more useful.

**Comment by donutmonger** [comment]
I am seeing a similar issue using `lycheeorg/lychee:v4.2.2`. From what I can tell my settings are appropriate as they are being picked up by the diagnostics page: 
![2021-04-18-01:24:28](https://user-images.githubusercontent.com/3676616/115137712-d633a200-9fe4-11eb-8512-098820d876c3.png)

But whenever I try and upload an image greater than 2M I am met with this error:
![2021-04-18-01:19:26](https://user-images.githubusercontent.com/3676616/115137654-8d7be900-9fe4-11eb-9310-227b50df9522.png)

After seeing this issue appear with default config, I tried providing a custom `nginx.conf` (based on the `default.conf` that is checked in) and upping the limits. This had no effect so next I tried providing a custom `php.ini` to `/etc/php/7.4/fpm/php.ini` but that also did not work.

**Comment by d7415** [comment]
> @d7415 I am seeing a similar issue using `lycheeorg/lychee:v4.2.2`.

If it's not the same issue please open a new issue.

How big is your image? Are you accessing the Docker image directly?

**Comment by donutmonger** [comment]
> Are you accessing the Docker image directly?

Ah that was it, thank you! I'm running in k8s and have an nginx ingress controller. The upload max file size limit was set to the default there and it was causing the issue. Setting `nginx.ingress.kubernetes.io/proxy-body-size: 512m` in my ingress annotations fixed it.
